### ISSUE TITLE
Change the default python interpreter in Paraview

### ISSUE THREAD

**Issue by s1291** [tianyikillua/paraview-meshio#1]
I am running Paraview 5.6.2 on Windows. In order to setup your plugin I need to set the default Python interpreter in Paraview (Currently it is using python 2.7.15):
![paraview-python-interpreter](https://user-images.githubusercontent.com/17838489/67420277-98f87a80-f5ce-11e9-8073-01328970a8b3.png)
How to set Python3 as the default python interpreter?
Thanks

**Comment by tianyikillua** [comment]
I suggest [downloading](https://www.paraview.org/download/) the latest 5.7.0 version for Windows, which includes (finally) Python 3.7.

Otherwise you'll need to compile yourself ParaView with your own Python 3. Good luck!

**Comment by s1291** [comment]
@tianyikillua : Thank you, I was about to edit the post because I am downloading the last version 5.7.
Thanks

**Comment by s1291** [comment]
@tianyikillua : I have installed Paraview 5.7. Fortunately it works as expected! Surprisingly it opens also the `*.med` files that I reported in this [issue](https://github.com/nschloe/meshio/issues/478).

**Comment by tianyikillua** [comment]
...So I suppose you also installed the `h5py` library into ParaView right? Anyway great news!

**Comment by s1291** [comment]
Yes, I copied `meshio`, `h5py` and `netCDF4` modules to `C:\Program Files\ParaView 5.7.0-MPI-Windows-Python3.7-msvc2015-64bit\bin\Lib\site-packages\`
