### ISSUE TITLE
How to load Ansys .msh file instead of gmsh .msh file

### ISSUE THREAD

**Issue by s1291** [tianyikillua/paraview-meshio#2]
When I try to load Ansys `.msh` file it fails. Looking to the error message seems that it assumes a `GMSH` file format.

How can I specify  Ansys instead of gmsh?

* The ansys `.msh` file: [pitzDaily.zip](https://github.com/tianyikillua/paraview-meshio-reader/files/3764264/pitzDaily.zip)
* The error message: [paraview-error.log](https://github.com/tianyikillua/paraview-meshio-reader/files/3764273/paraview-error.log)

Thanks

**Comment by s1291** [comment]
My guess is that `meshio` should look to the first few lines of the `.msh` file, if it contains parentheses then it is an `ansys` file format otherwise it is a `gmsh`. both `ansys-ascii` and `ansys-binary` contain parentheses. This might be a naive approach but it may work.

**Comment by tianyikillua** [comment]
Yes either we solve it upstream in `meshio`, either we should provide a format selector in this plugin. I'll look into the 2nd option.

**Comment by tianyikillua** [comment]
With 04b6a176619f88d214248a8a8d14841d696ea840, you now have a file format selector.

![2019-10-24 12_23_41-ParaView 5 7 0](https://user-images.githubusercontent.com/4027283/67477106-ac9cf300-f659-11e9-853e-455723293c90.png)

**Comment by s1291** [comment]
@tianyikillua: I couldn't see that option `File Format`!

![paraview](https://user-images.githubusercontent.com/17838489/67479383-38b11980-f65e-11e9-9aea-8e7184c2f32f.png)

**Comment by tianyikillua** [comment]
Have you replaced your current `meshioReader.py` by the latest version? You may also need to click *Reload Python Module*.

**Comment by s1291** [comment]
@tianyikillua : Yes of course I updated to the latest version, removed the old plugin and loaded it again.

**Comment by s1291** [comment]
@tianyikillua :Sorry,  I had a problem with paraview. Now it works! 
Thank you
